#!/usr/bin/env node
'use strict';
require('./lib/fatal-guard.js')('used-offbrand-739.test.js');
// (v9.7.739) Toyota Baytown lead 2091436932, 9/29 (log263, capture 214583f3, dump ff3719d8). The lead's vehicle is
// "Chevrolet Silverado (Used)", the Pam phone-agent note says "a new Chevrolet Silverado", and the store holds four
// used Silverados. The OFF-FRANCHISE block listed the first two used Chevrolets it found (a Malibu, an Impala) and
// said not to ask year or trim; the BRAND MISMATCH block said "NEVER offer to show them the Chevrolet -- we do not
// carry it"; the draft pivoted to a Tundra. Gil: "VOI is a used Silverado. message is trying to pivot incorrectly
// instead of working pre-owned angle." Executes the shipped populateFromData and buildUserPrompt with a stubbed
// inventory feed. Placeholder names, numbers and stock numbers only.
//
// Usage: node tests/used-offbrand-739.test.js <dev popup.js> <commercial popup.js>
const path = require('path'), vm = require('vm');
const loadPopup = require('./helpers/load-popup.js');
const BUILDS = process.argv.slice(2).filter(a => /popup\.js$/.test(a));
if (!BUILDS.length) { console.error('usage: used-offbrand-739.test.js <popup.js> [popup.js...]'); process.exit(2); }
let pass = 0, fail = 0;
function check(name, fn, want) {
  let got; try { got = fn(); } catch (e) { got = 'THREW: ' + e.message; }
  const g = JSON.stringify(got), w = JSON.stringify(want);
  if (g === w) { pass++; console.log('  ok   ' + name); }
  else { fail++; console.log('  FAIL ' + name + '\n        expected ' + w + '\n        got      ' + g); }
}
const unit = (y, model, stock) => ({ stock, vehicle: y + ' Chevrolet ' + model, year: y, make: 'Chevrolet', model, condition: 'used' });
const MALIBU = unit(2021, 'Malibu LT', 'TEST001A'), IMPALA = unit(2019, 'Impala LT', 'TEST002A');
const SILV = [unit(2024, 'Silverado 1500 RST', 'TEST003A'), unit(2021, 'Silverado 1500 LT LT1', 'TEST004A')];
const NOTE = 'Lead generated by Pam phone agent for a new Chevrolet Silverado.';

for (const f of BUILDS) {
  console.log('\n' + path.basename(path.dirname(f)) + '/' + path.basename(f));
  const sb = loadPopup(f, { withAuth: true });
  const setInv = (units) => { sb.__u = units; vm.runInContext('_lpValueFactCache["6189"] = globalThis.__u ? { inv: { units: globalThis.__u } } : {};', sb); };
  const lead = (over) => Object.assign({ name: 'Test Buyer', agent: 'Agent Name', phone: '(555) 010-0199', vehicle: 'Chevrolet Silverado', condition: 'Pre-Owned',
    dealerId: '6189', store: 'Community Toyota Baytown', leadSource: 'Pam Ai Inbound Lead', convState: 'first-touch', leadAgeDays: 0,
    hasOutbound: true, hasCustomerReply: false, totalNoteCount: 4, relationshipSignals: {}, history: '', context: '',
    conversationBrief: '', lastInboundMsg: NOTE }, over || {});
  const pfd = (units, over) => { setInv(units); vm.runInContext('activeFlags = new Set(); leadContext = "";', sb); sb.populateFromData(lead(over)); return vm.runInContext('leadContext', sb); };
  const up = (units, over) => { setInv(units); vm.runInContext('leadContext = ""; window._lpNoApptLeadId = "";', sb); return sb.__lp.buildUserPrompt(lead(over)); };

  console.log(' 1. the off-franchise block leads with the requested model when we hold it used:');
  const c = pfd([MALIBU, IMPALA].concat(SILV));
  check('it names the used Silverados, not the first two Chevrolets on the list', () =>
    [/PRE-OWNED CHEVROLET SILVERADO IN STOCK — THIS IS THE ANGLE/.test(c), /2024 Chevrolet Silverado 1500 RST \(stock TEST003A\); 2021 Chevrolet Silverado 1500 LT LT1 \(stock TEST004A\)/.test(c),
     /Malibu|Impala/.test(c)], [true, true, false]);
  check('...offered as pre-owned, year/configuration/budget may be asked, no pivot to a Toyota, and honest about new', () =>
    [/offered as pre-owned \(never as new\), and ask which fits: year, configuration or budget is a fair question/.test(c),
     /Do NOT pivot them to a Toyota instead/.test(c), /be straight that this is a Toyota store and cannot get a new Chevrolet/.test(c),
     /Do NOT say you will "check what we have"/.test(c)], [true, true, true, false]);
  check('control: no Silverado on the lot -> the original off-franchise block', () => {
    const t = pfd([MALIBU, IMPALA]); return [/OFF-FRANCHISE REQUEST — READ BEFORE PROMISING ANYTHING/.test(t), /PRE-OWNED CHEVROLET SILVERADO/.test(t)]; }, [true, false]);

  console.log(' 2. brand mismatch does not fire on a used vehicle of a make we stock:');
  check('used Silverado, used Chevrolets in stock -> no BRAND MISMATCH block', () => /⚠ BRAND MISMATCH/.test(up(SILV)), false);
  check('control: the same vehicle marked New -> BRAND MISMATCH as before', () => /⚠ BRAND MISMATCH/.test(up(SILV, { condition: 'New' })), true);
  check('control: no Chevrolets in stock -> BRAND MISMATCH as before', () => /⚠ BRAND MISMATCH/.test(up([])), true);
}
console.log('\n' + pass + ' passed, ' + fail + ' failed');
process.exit(fail ? 1 : 0);
